# Please use an online yaml validator
# There is a lot more customization that you can do. You have to read the doumentation for that.

HairLengths:
  - Dashes: 0
    Length: 6
  - Dashes: 1
    Length: 6
  - Dashes: 2
    Length: 6
  - Dashes: 3
    Length: 6

HairColors:
  - Dashes: 0
    Color: "6E6E6E"
  - Dashes: 1
    Color: "F9855C"
  - Dashes: 2
    Color: "FFA1FF"
  - Dashes: 3
    Color: "FF0000"
  - Dashes: 4
    Color: "86CECB"
HairFlash: true # Enables the distracting white flash that happens when your dash count changes.
OutlineColor: "040000" # This specifies the hair outline color, not the sprite outline.
