# Please use an online yaml validator
# There is a lot more customization that you can do. You have to read the doumentation for that.

HairLengths:
  - Dashes: 0
    Length: 5
  - Dashes: 1
    Length: 5
  - Dashes: 2
    Length: 5
  - Dashes: 3
    Length: 5

HairColors:
  - Dashes: 0
    Color: "FFFFFF"
  - Dashes: 1
    Color: "FFFFFF"
  - Dashes: 2
    Color: "FFFFFF"
  - Dashes: 3
    Color: "FFFFFF"
  - Dashes: 4
    Color: "FFFFFF"
HairFlash: true # Enables the distracting white flash that happens when your dash count changes.
OutlineColor: "040000" # This specifies the hair outline color, not the sprite outline.
